Repository wix/Detox, pull requests merged in 2018-09, with the labels that each got.

#928 Fix typo
  docs/APIRef.DeviceObjectAPI.md
Labels: type: documentation

#950 Make compatible with BSD + GNU mktemp
  detox/scripts/build_universal_framework.sh
Labels: type: accepted/enhancement, user: more info needed

#953 hotfix: added a retry on install (XCode 10 issue)
  detox/src/devices/ios/AppleSimUtils.js
Labels: type: accepted/discussion, 📌 pinned

#873 Implement the capability to change the language between tests
  detox/src/devices/Device.js
  detox/src/devices/Device.test.js
  detox/src/devices/drivers/AndroidDriver.js
  detox/src/devices/drivers/SimulatorDriver.js
  detox/src/devices/ios/AppleSimUtils.js
  detox/src/devices/ios/AppleSimUtils.test.js
  detox/src/devices/ios/__snapshots__/AppleSimUtils.test.js.snap
  detox/test/e2e/06.device.test.js
  detox/test/src/Screens/LanguageScreen.js
  detox/test/src/Screens/index.js
  detox/test/src/app.js
  docs/APIRef.DeviceObjectAPI.md
Labels: type: accepted/enhancement
