Repository wix/Detox, pull requests merged in 2018-08, with the labels that each got.

#872 iOS: Add RN Loading JS Idling Resource
  detox/ios/Detox.xcodeproj/project.pbxproj
  detox/ios/Detox/EarlGreyStatistics.m
  detox/ios/Detox/GREYIdlingResourcePrettyPrint.h
  detox/ios/Detox/GREYIdlingResourcePrettyPrint.m
  detox/ios/Detox/ReactNativeSupport.m
  detox/ios/Detox/WXRNLoadIdlingResource.h
  detox/ios/Detox/WXRNLoadIdlingResource.m
  detox/test/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme
Labels: type: accepted/discussion, type: internal, 📌 pinned

#882 Add additional synchronization points for CFRunLoopPerformBlock
  detox/ios/Detox/ReactNativeSupport.m
  detox/ios/Detox/WXRunLoopIdlingResource.m
Labels: 📌 pinned

#848 Internal changes to artifacts subsystem in Detox and bugfixes
  detox/src/Detox.js
  detox/src/Detox.test.js
  detox/src/__snapshots__/configuration.test.js.snap
  detox/src/artifacts/ArtifactsManager.js
  detox/src/artifacts/ArtifactsManager.test.js
  detox/src/artifacts/__snapshots__/ArtifactsManager.test.js.snap
  detox/src/artifacts/log/LogArtifactPlugin.js
  detox/src/artifacts/log/android/ADBLogcatPlugin.js
  detox/src/artifacts/log/android/ADBLogcatRecording.js
  detox/src/artifacts/log/ios/SimulatorLogPlugin.js
  detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js
  detox/src/artifacts/log/ios/SimulatorLogRecording.js
  detox/src/artifacts/log/ios/__snapshots__/SimulatorLogPlugin.test.js.snap
  detox/src/artifacts/screenshot/ADBScreencapPlugin.js
  detox/src/artifacts/screenshot/SimulatorScreenshotPlugin.js
  detox/src/artifacts/templates/plugin/ArtifactPlugin.js
  detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js
  detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.js
  detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.test.js
  detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js
  detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.test.js
  detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.js
  detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.test.js
  detox/src/artifacts/templates/plugin/__mocks__/ArtifactsApi.mock.js
  detox/src/artifacts/templates/plugin/__snapshots__/ArtifactPlugin.test.js.snap
  detox/src/artifacts/video/ADBScreenrecorderArtifact.js
  detox/src/artifacts/video/ADBScreenrecorderPlugin.js
  detox/src/artifacts/video/SimulatorRecordVideoPlugin.js
  detox/src/configuration.test.js
  detox/src/devices/Device.js
  detox/src/devices/Device.test.js
  detox/src/devices/__snapshots__/Device.test.js.snap
  detox/src/devices/android/Emulator.js
  detox/src/devices/drivers/AndroidDriver.js
  detox/src/devices/drivers/AttachedAndroidDriver.js
  detox/src/devices/drivers/DeviceDriverBase.js
  detox/src/devices/drivers/EmulatorDriver.js
  detox/src/devices/drivers/IosDriver.js
  detox/src/devices/drivers/SimulatorDriver.js
  detox/src/devices/ios/AppleSimUtils.js
  detox/src/devices/ios/AppleSimUtils.test.js
  detox/src/devices/ios/__snapshots__/AppleSimUtils.test.js.snap
  detox/src/devices/ios/xcrunSimctlList.mock.json
  detox/src/utils/AsyncEmitter.js
  detox/src/utils/AsyncEmitter.test.js
  detox/src/utils/__snapshots__/AsyncEmitter.test.js.snap
  detox/src/utils/__snapshots__/exec.test.js.snap
  detox/src/utils/environment.js
  detox/src/utils/exec.interruptProcess.test.js
  detox/src/utils/exec.js
  detox/src/utils/exec.test.js
  detox/src/utils/interruptProcess.js
Labels: type: internal, 📌 pinned

#910 make android green again
  detox/android/detox/build.gradle
  detox/test/android/app/build.gradle
  detox/test/android/build.gradle
  detox/test/android/gradle/wrapper/gradle-wrapper.properties
  detox/test/package.json
  detox/test/scripts/__snapshots__/verify_artifacts_are_not_missing.android.test.js.snap
  scripts/ci.android.sh
Labels: type: internal
