Repository wix/Detox, pull requests merged in 2019-06, with the labels that each got.

#1428 Reimplemented SimulatorLogPlugin to use log stream
  detox/src/artifacts/log/LogArtifactPlugin.js
  detox/src/artifacts/log/ios/SimulatorLogPlugin.js
  detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js
  detox/src/artifacts/log/ios/SimulatorLogRecording.js
  detox/src/devices/ios/AppleSimUtils.js
  detox/src/utils/exec.js
  detox/src/utils/exec.test.js
Labels: type: accepted/enhancement, z_domain: artifacts

#1431 Cleanup: Remove residue of pre Xcode 9 simulator boot logic
  detox/src/devices/ios/AppleSimUtils.js
  detox/test/e2e/16.location.test.js
Labels: z_platform: ios

#1348 Introduce basic Detox Instruments demo app
  detox/ios/Detox/DetoxInstrumentsManager.m
  detox/ios/Detox/EarlGreyStatistics.m
  detox/ios/Detox/GREYIdlingResourcePrettyPrint.m
  examples/demo-react-native-detox-instruments/.buckconfig
  examples/demo-react-native-detox-instruments/.flowconfig
  examples/demo-react-native-detox-instruments/.gitignore
  examples/demo-react-native-detox-instruments/.watchmanconfig
  examples/demo-react-native-detox-instruments/README.md
  examples/demo-react-native-detox-instruments/app.js
  examples/demo-react-native-detox-instruments/e2e/example.spec.js
  examples/demo-react-native-detox-instruments/e2e/init.js
  examples/demo-react-native-detox-instruments/e2e/mocha.opts
  examples/demo-react-native-detox-instruments/index.android.js
  examples/demo-react-native-detox-instruments/index.js
  examples/demo-react-native-detox-instruments/ios/example.xcodeproj/project.pbxproj
  examples/demo-react-native-detox-instruments/ios/example.xcodeproj/xcshareddata/xcschemes/example Release.xcscheme
  examples/demo-react-native-detox-instruments/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme
  examples/demo-react-native-detox-instruments/ios/example/AppDelegate.h
  examples/demo-react-native-detox-instruments/ios/example/AppDelegate.m
  examples/demo-react-native-detox-instruments/ios/example/Base.lproj/LaunchScreen.xib
  examples/demo-react-native-detox-instruments/ios/example/Images.xcassets/AppIcon.appiconset/Contents.json
  examples/demo-react-native-detox-instruments/ios/example/Info.plist
  examples/demo-react-native-detox-instruments/ios/example/main.m
  examples/demo-react-native-detox-instruments/ios/exampleTests/Info.plist
  examples/demo-react-native-detox-instruments/ios/exampleTests/exampleTests.m
  examples/demo-react-native-detox-instruments/metro.config.js
  examples/demo-react-native-detox-instruments/package.json
  lerna.json
  scripts/demo-projects.ios.sh
Labels: type: accepted/enhancement

#1430 Merge demo binaries
  detox/ios/Detox/DetoxInstrumentsManager.m
  examples/demo-react-native-detox-instruments/.gitignore
  examples/demo-react-native-detox-instruments/e2e/example.spec.js
  examples/demo-react-native-detox-instruments/package.json
  examples/demo-react-native-jest/.buckconfig
  examples/demo-react-native-jest/.flowconfig
  examples/demo-react-native-jest/.gitattributes
  examples/demo-react-native-jest/.watchmanconfig
  examples/demo-react-native-jest/App.js
  examples/demo-react-native-jest/__tests__/App.js
  examples/demo-react-native-jest/android/app/BUCK
  examples/demo-react-native-jest/android/app/build.gradle
  examples/demo-react-native-jest/android/app/keystore.jks
  examples/demo-react-native-jest/android/app/proguard-rules.pro
  examples/demo-react-native-jest/android/app/src/androidTest/java/com/demoreactnativejest/test/DetoxTest.java
  examples/demo-react-native-jest/android/app/src/main/AndroidManifest.xml
  examples/demo-react-native-jest/android/app/src/main/java/com/demoreactnativejest/MainActivity.java
  examples/demo-react-native-jest/android/app/src/main/java/com/demoreactnativejest/MainApplication.java
  examples/demo-react-native-jest/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  examples/demo-react-native-jest/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  examples/demo-react-native-jest/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  examples/demo-react-native-jest/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  examples/demo-react-native-jest/android/app/src/main/res/values/strings.xml
  examples/demo-react-native-jest/android/app/src/main/res/values/styles.xml
  examples/demo-react-native-jest/android/build.gradle
  examples/demo-react-native-jest/android/gradle.properties
  examples/demo-react-native-jest/android/gradle/wrapper/gradle-wrapper.jar
  examples/demo-react-native-jest/android/gradle/wrapper/gradle-wrapper.properties
  examples/demo-react-native-jest/android/gradlew
  examples/demo-react-native-jest/android/gradlew.bat
  examples/demo-react-native-jest/android/keystores/BUCK
  examples/demo-react-native-jest/android/keystores/debug.keystore.properties
  examples/demo-react-native-jest/android/settings.gradle
  examples/demo-react-native-jest/app.json
  examples/demo-react-native-jest/index.js
  examples/demo-react-native-jest/ios/DemoReactNativeJest-tvOS/Info.plist
  examples/demo-react-native-jest/ios/DemoReactNativeJest-tvOSTests/Info.plist
  examples/demo-react-native-jest/ios/DemoReactNativeJest.xcodeproj/project.pbxproj
  examples/demo-react-native-jest/ios/DemoReactNativeJest.xcodeproj/xcshareddata/xcschemes/DemoReactNativeJest-tvOS.xcscheme
  examples/demo-react-native-jest/ios/DemoReactNativeJest.xcodeproj/xcshareddata/xcschemes/DemoReactNativeJest.xcscheme
  examples/demo-react-native-jest/ios/DemoReactNativeJest/AppDelegate.h
  examples/demo-react-native-jest/ios/DemoReactNativeJest/AppDelegate.m
  examples/demo-react-native-jest/ios/DemoReactNativeJest/Base.lproj/LaunchScreen.xib
  examples/demo-react-native-jest/ios/DemoReactNativeJest/Images.xcassets/AppIcon.appiconset/Contents.json
  examples/demo-react-native-jest/ios/DemoReactNativeJest/Info.plist
  examples/demo-react-native-jest/ios/DemoReactNativeJest/main.m
  examples/demo-react-native-jest/ios/DemoReactNativeJestTests/DemoReactNativeJestTests.m
  examples/demo-react-native-jest/ios/DemoReactNativeJestTests/Info.plist
  examples/demo-react-native-jest/package.json
  examples/demo-react-native-jest/rn-cli.config.js
  examples/demo-react-native/package.json
  scripts/demo-projects.android.sh
  scripts/demo-projects.ios.sh
  scripts/demo-projects.sh
Labels: type: accepted/enhancement, z_domain: internal

#1144 refactor: allow technically to control multiple detox instances
  detox/package.json
  detox/src/Detox.js
  detox/src/Detox.test.js
  detox/src/DetoxExportWrapper.js
  detox/src/__snapshots__/Detox.test.js.snap
  detox/src/android/expect.js
  detox/src/android/expect.test.js
  detox/src/devices/drivers/AndroidDriver.js
  detox/src/devices/drivers/DeviceDriverBase.js
  detox/src/devices/drivers/IosDriver.js
  detox/src/exportWrapper.js
  detox/src/exportWrapper.test.js
  detox/src/index.js
  detox/src/index.test.js
  detox/src/ios/expect.js
  detox/src/ios/expect.test.js
  detox/src/platform.js
  detox/src/platform.test.js
Labels: type: accepted/enhancement

#1440 Updating Guide.Mocking with Metro breaking changes
  docs/Guide.Mocking.md
Labels: z_domain: documentation

#1472 Upgrade to RN 0.59.9 to support Xcode 11
  detox/test/index.ios.js
  detox/test/package.json
Labels: type: accepted/enhancement

#1480 Implement a new typing action
  detox/ios/Detox/GREYActions+Detox.m
  detox/test/e2e/03.actions.test.js
Labels: type: accepted/enhancement
