Repository wix/Detox, pull requests merged in 2019-08, with the labels that each got.

#1580 Improve robustness of scroller by increasing initial post-scrolling idle lookahead window
  detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java
Labels: z_platform: android

#1516 Remove iOS 9 support, remove legacy notification API
  detox/ios/Detox.xcodeproj/project.pbxproj
  detox/ios/Detox.xcodeproj/xcshareddata/xcschemes/Detox.xcscheme
  detox/ios/Detox/DetoxAppDelegateProxy.h
  detox/ios/Detox/DetoxAppDelegateProxy.m
  detox/ios/Detox/DetoxManager.m
  detox/ios/Detox/DetoxUserActivityDispatcher.swift
  detox/ios/Detox/DetoxUserNotificationDispatcher.swift
  detox/ios/DetoxUserNotificationTests/DetoxUserNotificationTests.swift
  detox/ios/DetoxUserNotificationTests/LegacyApiAppDelegate.swift
  detox/ios/DetoxUserNotificationTests/TestableAppDelegate.swift
  detox/ios/DetoxUserNotificationTests/UNApiAppDelegate.swift
  detox/src/DetoxConstants.js
  docs/APIRef.MockingUserNotifications.md
  docs/Guide.Migration.md
Labels: type: accepted/enhancement

#1598 Text input improvements
  detox/ios/Detox/GREYActions+Detox.m
  detox/test/e2e/03.actions.test.js
  detox/test/ios/example.xcodeproj/project.pbxproj
  detox/test/src/Screens/ActionsScreen.js
Labels: type: accepted/enhancement

#1612 Log reflection errors from looper introspection
  detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java
Labels: user: more info needed
