Repository wix/Detox, pull requests merged in 2020-03, with the labels that each got.

#1944 Introduce unified custom logger to log user events using bunyan
  detox/local-cli/test.js
  detox/src/utils/callsites.js
  detox/src/utils/callsites.test.js
  detox/src/utils/customConsoleLogger.js
  detox/src/utils/customConsoleLogger.test.js
  detox/src/utils/logger.js
  docs/APIRef.DetoxCLI.md
Labels: type: accepted/enhancement, visibility/ux

#1954 Create prebuilt Detox framework
  .gitignore
  README.md
  detox/ios/Detox.xcodeproj/project.pbxproj
  detox/ios/Detox/DetoxUserActivityDispatcher.swift
  detox/ios/Detox/DetoxUserNotificationDispatcher.swift
  detox/ios/Detox/GREYMatchers+Detox.m
  detox/scripts/build.js
  detox/scripts/build_framework.ios.sh
  detox/scripts/build_universal_framework.sh
  detox/scripts/pack_ios.js
  detox/scripts/pack_ios.sh
  package.json
  scripts/ci.ios-release.sh
  scripts/ci.publish.js
Labels: type: accepted/enhancement, z_domain: internal

#1982 Limit emu's skin config patching to <28
  detox/src/devices/drivers/EmulatorDriver.js
Labels: type: accepted/bug, z_platform: android

#1984 Refactor bloated emulator driver according to sub-concerns
  detox/src/devices/drivers/AdbDevicesHelper.js
  detox/src/devices/drivers/AdbDevicesHelper.test.js
  detox/src/devices/drivers/EmulatorDriver.js
  detox/src/devices/drivers/EmulatorLookupHelper.js
  detox/src/devices/drivers/EmulatorLookupHelper.test.js
Labels: type: accepted/enhancement
