Repository wix/Detox, pull requests merged in 2021-09, with the labels that each got.

#2966 Remove bintray sunset hacks
  detox/android/build.gradle
  detox/android/detox/build.gradle
  detox/test/android/app/build.gradle
  detox/test/android/build.gradle
  detox/test/android/libs/proguard-annotations-1.14.1.jar
  examples/demo-react-native/android/app/build.gradle
  examples/demo-react-native/android/build.gradle
  examples/demo-react-native/android/libs/proguard-annotations-1.14.1.jar
Labels: type: accepted/enhancement, z_domain: internal

#2977 docs: Duration arg in longPress()
  detox/index.d.ts
  docs/APIRef.ActionsOnElement.md
Labels: z_domain: documentation

#2965 feat: CLI and JS config parity
  detox/index.d.ts
  detox/local-cli/test.js
  detox/local-cli/test.test.js
  detox/local-cli/utils/testCommandArgs.js
  detox/local-cli/utils/warnings.js
  detox/src/artifacts/templates/artifact/Artifact.test.js
  detox/src/configuration/collectCliConfig.js
  detox/src/configuration/collectCliConfig.test.js
  detox/src/configuration/composeDeviceConfig.js
  detox/src/configuration/composeDeviceConfig.test.js
  detox/src/configuration/configurations.mock.js
  detox/src/configuration/index.test.js
  detox/src/configuration/utils/warnings.js
  detox/src/devices/Device.js
  detox/src/devices/Device.test.js
  detox/src/devices/drivers/DeviceDriverBase.js
  detox/src/devices/drivers/android/attached/AttachedAndroidDriver.js
  detox/src/devices/drivers/android/attached/AttachedAndroidDriver.test.js
  detox/src/devices/drivers/android/emulator/EmulatorDriver.js
  detox/src/devices/drivers/android/emulator/EmulatorVersionResolver.js
  detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.js
  detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.test.js
  detox/src/devices/drivers/android/emulator/helpers/EmulatorLauncher.js
  detox/src/devices/drivers/android/exec/EmulatorExec.js
  detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js
  detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js
  detox/src/devices/drivers/android/genycloud/helpers/GenyRecipeQuerying.js
  detox/src/devices/drivers/android/genycloud/helpers/GenyRecipeQuerying.test.js
  detox/src/devices/drivers/ios/SimulatorDriver.js
  detox/src/devices/drivers/ios/SimulatorDriver.test.js
  detox/src/devices/drivers/ios/tools/AppleSimUtils.js
  detox/src/errors/DetoxConfigErrorComposer.js
  detox/src/errors/DetoxConfigErrorComposer.test.js
  detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap
  detox/src/utils/argparse.js
  detox/test/e2e/detox.config.js
  detox/test/integration/stub/StubDriver.js
  docs/APIRef.Configuration.md
Labels: type: accepted/enhancement, z_domain: ux
