Repository wix/Detox, pull requests merged in 2021-02, with the labels that each got.

#2613 Introduce device.setLaunchArg()
  detox/index.d.ts
  detox/src/devices/Device.js
  detox/src/devices/Device.test.js
  detox/test/e2e/22.launch-args.test.js
  docs/APIRef.DeviceObjectAPI.md
Labels: type: triage/enhancement

#2600 Drag and drop
  detox/index.d.ts
  detox/ios/Detox/Actions/NSObject+DetoxActions.h
  detox/ios/Detox/Actions/NSObject+DetoxActions.m
  detox/ios/Detox/Actions/UIScrollView+DetoxActions.m
  detox/ios/Detox/AppleTouchEvents/DTXSyntheticEvents.h
  detox/ios/Detox/AppleTouchEvents/DTXSyntheticEvents.m
  detox/ios/Detox/DetoxAppDelegateProxy.m
  detox/ios/Detox/Invocation/Action.swift
  detox/ios/Detox/Invocation/Element.swift
  detox/src/ios/expectTwo.js
  detox/src/ios/expectTwo.test.js
  detox/src/ios/expectTwoApiCoverage.test.js
  detox/test/e2e/28.drag-and-drop.test.js
  detox/test/ios/DragDropTableViewController.h
  detox/test/ios/DragDropTableViewController.m
  detox/test/ios/example.xcodeproj/project.pbxproj
  detox/test/ios/example/AppDelegate.m
  detox/test/ios/example/DragDropViewController.h
  detox/test/ios/example/DragDropViewController.m
  detox/test/ios/example/NativeModule.m
  detox/test/src/Screens/index.js
  detox/test/src/app.js
  docs/APIRef.ActionsOnElement.md
Labels: type: accepted/enhancement, z_platform: ios

#2624 Introduce launch-args modification API
  detox/index.d.ts
  detox/src/devices/Device.js
  detox/src/devices/Device.test.js
  detox/src/devices/LaunchArgs.js
  detox/src/devices/LaunchArgs.test.js
  detox/test/detox.config.js
  detox/test/e2e/22.launch-args.test.js
  docs/APIRef.Configuration.md
  docs/APIRef.DetoxCLI.md
  docs/APIRef.DeviceObjectAPI.md
  docs/APIRef.LaunchArgs.md
  docs/Guide.Mocking.md
Labels: type: accepted/discussion

#2644 Fix launch-arguments editing bug
  detox/src/devices/Device.js
  detox/src/devices/LaunchArgs.test.js
  detox/src/devices/LaunchArgsEditor.js
  detox/src/devices/LaunchArgsEditor.test.js
  docs/APIRef.LaunchArgs.md
Labels: type: accepted/bug
