Repository wix/Detox, pull requests merged in 2021-11, with the labels that each got.

#3038 feat: device.appLaunchArgs.shared
  detox/index.d.ts
  detox/src/devices/runtime/LaunchArgsEditor.js
  detox/src/devices/runtime/RuntimeDevice.js
  detox/src/devices/runtime/utils/LaunchArgsEditor-deprecation.test.js
  detox/src/devices/runtime/utils/LaunchArgsEditor.js
  detox/src/devices/runtime/utils/LaunchArgsEditor.test.js
  detox/src/devices/runtime/utils/ScopedLaunchArgsEditor.js
  detox/src/devices/runtime/utils/Storage.js
  detox/src/devices/runtime/utils/__snapshots__/LaunchArgsEditor.test.js.snap
  detox/test/types/detox-global-tests.ts
  docs/APIRef.DeviceObjectAPI.md
Labels: type: accepted/enhancement

#3083 feat(DocSearch): integrate Detox website with Algolia DocSerach.
  website/docusaurus.config.js
  website/package.json
Labels: z_domain: documentation

#3009 types: add typings for element(...).getAttributes()
  detox/index.d.ts
  detox/test/e2e/33.attributes.test.js
  detox/test/src/Screens/AttributesScreen.js
  detox/test/types/detox-global-tests.ts
Labels: type: accepted/enhancement, user: more info needed, z_domain: documentation

#3111 Validate proper app vs. test APK config
  detox/package.json
  detox/src/devices/common/drivers/android/exec/AAPT.js
  detox/src/devices/common/drivers/android/exec/AAPT.test.js
  detox/src/devices/common/drivers/android/exec/__mocks__/aapt-results.js
  detox/src/devices/common/drivers/android/exec/__snapshots__/AAPT.test.js.snap
  detox/src/devices/common/drivers/android/tools/APKPath.js
  detox/src/devices/common/drivers/android/tools/APKPath.test.js
  detox/src/devices/common/drivers/android/tools/ApkValidator.js
  detox/src/devices/common/drivers/android/tools/ApkValidator.test.js
  detox/src/devices/common/drivers/android/tools/__snapshots__/ApkValidator.test.js.snap
  detox/src/devices/common/drivers/android/tools/apk.js
  detox/src/devices/common/drivers/android/tools/apk.test.js
  detox/src/devices/runtime/drivers/android/AndroidDriver.js
  detox/src/devices/runtime/drivers/android/AndroidDriver.test.js
  detox/src/devices/runtime/drivers/android/__snapshots__/AndroidDriver.test.js.snap
  detox/src/devices/runtime/drivers/android/emulator/EmulatorDriver.js
  detox/src/devices/runtime/drivers/android/genycloud/GenyCloudDriver.js
  detox/src/devices/runtime/drivers/android/genycloud/GenyCloudDriver.test.js
  detox/src/devices/runtime/factories/android.js
  detox/src/errors/DetoxRuntimeError.js
  detox/src/servicelocator/android/index.js
Labels: type: accepted/enhancement, z_platform: android
